AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS Hail Quickstart (qs-1qp776mh2)"

Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into a new VPC"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Network Configuration"
        Parameters:
          - "VPCTarget"
          - "VPCCIDR"
          - "VPCId"
          - "VPCSubnetId"
          - "VPCSubnetType"
      - Label:
          default: "Hail Configuration"
        Parameters:
          - "CreateHailBucket"
          - "HailS3BucketName"
          - "CreateSageMakerBucket"
          - "SageMakerS3BucketName"
          - "KMSEbsKeyArn"
      - Label:
          default: "Tagging Configuration"
        Parameters:
          - "TagEnvironmentType"
          - "TagOwner"
      - Label:
          default: "Identity and Access Management (Optional)"
        Parameters:
          - "UsePermissionBoundary"
          - "PermissionBoundaryARN"
          - "UseIamPrefix"
          - "IamPrefix"
          - "UseIamSuffix"
          - "IamSuffix"
      - Label:
          default: "AWS Quick Start Configuration"
        Parameters:
         - "QSS3BucketName"
         - "QSS3KeyPrefix"
         - "QSS3BucketRegion"

    ParameterLabels:
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      QSS3BucketRegion:
        default: Region of Quickstart bucket
      KMSEbsKeyArn:
        default: "EBS KMS Key ARN (Optional)"
      HailS3BucketName:
        default: "Hail S3 bucket name"
      CreateHailBucket:
        default: "Create Hail S3 bucket"
      SageMakerS3BucketName:
        default: "Sagemaker home directory S3 bucket name"
      CreateSageMakerBucket:
        default: "Create SageMaker home directory S3 bucket"
      TagOwner:
        default: "Owner"
      TagEnvironmentType:
        default: "Environment type"
      VPCTarget:
        default: "Virtual Private Cloud (VPC) target"
      VPCCIDR:
        default: "New VPC CIDR (Optional)"
      VPCId:
        default: "Existing VPC ID"
      VPCSubnetId:
        default: "Existing Subnet ID"
      VPCSubnetType:
        default: "Existing Subnet type"
      UsePermissionBoundary:
        default: "Use Permission Boundary"
      PermissionBoundaryARN:
        default: "Permission Boundary ARN"
      UseIamPrefix:
        default: "Use prefix for roles and policies"
      IamPrefix:
        default: "Prefix to use for roles and policies"
      UseIamSuffix:
        default: "Use prefix for roles and policies"
      IamSuffix:
        default: "Prefix to use for roles and policies"

Parameters:

  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: "aws-quickstart"
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: "String"

  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: "quickstart-hail/"
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: "String"

  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted.'
    Type: String

  KMSEbsKeyArn:
    Description: "(Optional) The full KMS Key ARN if Region level EBS encryption is enabled. This does not automatically encrypt your AMI."
    Default: ""
    Type: "String"

  HailS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "The name of the S3 bucket that stores EMR logs, cluster manifests, and VEP configuration files."
    Type: "String"

  CreateHailBucket:
    Type: "String"
    Description: "Select No to use an existing bucket."
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  SageMakerS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    Description: "The name of the S3 bucket for common notebooks and SageMaker home directory backups."
    Type: "String"

  CreateSageMakerBucket:
    Type: "String"
    Description: "Select No to use an existing bucket."
    AllowedValues:
      - "yes"
      - "no"
    Default: "yes"

  TagEnvironmentType:
    AllowedValues:
      - "production"
      - "staging"
      - "development"
      - ""
    Default: ""
    Description: "(Optional) Environment type for default resource tagging."
    Type: "String"

  TagOwner:
    Type: "String"
    Description: "(Optional) Owner for default resource tagging. Suggested values are <User Name>, <Department Name>, <Project Name>, etc."
    Default: ""

  VPCTarget:
    Type: "String"
    Description: "Choose \"new\" to use the AWS VPC Quick Start to create a new VPC with three public and three private subnets. If you choose \"existing\", VPCId and SubnetId network parameters are required."
    AllowedValues:
      - "new"
      - "existing"
    Default: "existing"

  VPCCIDR:
    Type: "String"
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(1[6-9]|2[0-8]))$"
    Description: "Leave this blank if using an existing Virtual Private Cloud (VPC).  Otherwise, this is required for a new VPC. A /16 address space is recommended for a new VPC."
    Default: "10.0.0.0/16"

  VPCId:
    Description: "Required for existing VPC target.  Leave blank if using a 'New' VPC Target."
    Type: "AWS::EC2::VPC::Id"
    Default: ""

  VPCSubnetId:
    Description: "Required for an existing VPC target. Subnet ID in the existing VPC in which EMR Cluster and SageMaker Notebook Instances will be launched. A private subnet is recommended.  Leave blank if using a 'New' VPC Target."
    Type: "AWS::EC2::Subnet::Id"
    Default: ""

  VPCSubnetType:
    Description: "Required for an existing VPC target. Should match the type of subnet specified by Subnet Id. Type of subnet compute resources will be deployed in and also used to create custom AMIs. A private subnet is recommended. Leave blank if using a 'New' VPC Target."
    Type: "String"
    AllowedValues:
      - "public"
      - "private"
    Default: "private"

  UsePermissionBoundary:
    Type: "String"
    Description: "Select yes to use an existing Permission Boundary."
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"

  PermissionBoundaryARN:
    Description: "Enter Permission Boundary ARN."
    Type: "String"
    Default: ""

  UseIamPrefix:
    Type: "String"
    Description: "Select yes to incorporate a required prefix in IAM Role and Policy Names."
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"

  IamPrefix:
    Description: "Enter required IAM prefix."
    Type: "String"
    Default: ""

  UseIamSuffix:
    Type: "String"
    Description: "Select yes to incorporate a required suffix in IAM Role and Policy Names."
    AllowedValues:
      - "yes"
      - "no"
    Default: "no"

  IamSuffix:
    Description: "Enter required IAM suffix."
    Type: "String"
    Default: ""

Conditions:

    createVpc: !Equals [!Ref VPCTarget, "new"]
    UsingDefaultBucket: !Equals
    - !Ref QSS3BucketName
    - 'aws-quickstart'

Resources:

  core:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/hail-core.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        pHailBucket: !Ref HailS3BucketName
        pCreateHailBucket: !Ref CreateHailBucket
        pKmsEbsArn: !Ref KMSEbsKeyArn
        pSageMakerBucket: !Ref SageMakerS3BucketName
        pCreateSageMakerBucket: !Ref CreateSageMakerBucket
        pSubnetId: !If [createVpc, !GetAtt 'vpc.Outputs.PrivateSubnet1AID', !Ref VPCSubnetId]
        pSubnetType: !If [createVpc, "private", !Ref VPCSubnetType]
        pTagEnvironment: !Ref TagEnvironmentType
        pTagOwner: !Ref TagOwner
        pVpcId: !If [createVpc, !GetAtt 'vpc.Outputs.VPCID', !Ref VPCId]
        pUsePermissionBoundary: !Ref UsePermissionBoundary
        pPermissionBoundaryARN: !Ref PermissionBoundaryARN
        pUseIamPrefix: !Ref UseIamPrefix
        pIamPrefix: !Ref IamPrefix
        pUseIamSuffix: !Ref UseIamSuffix
        pIamSuffix: !Ref IamSuffix
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion
      TimeoutInMinutes: 5

  vpc:
    Type: "AWS::CloudFormation::Stack"
    Condition: createVpc
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones: !Join
        - ','
        - - !Select
            - 0
            - Fn::GetAZs: !Ref 'AWS::Region'
          - !Select
            - 1
            - Fn::GetAZs: !Ref 'AWS::Region'
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1CIDR: !Select [ 0, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet1ACIDR: !Select [ 1, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet1BCIDR: !Select [ 2, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PublicSubnet2CIDR: !Select [ 3, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet2ACIDR: !Select [ 4, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
        PrivateSubnet2BCIDR: !Select [ 5, !Cidr [ !Ref VPCCIDR, 6, 12 ]]
      TimeoutInMinutes: 10

Outputs:

  portfolio:
    Description: "Service catalog portfolio"
    Value: !GetAtt core.Outputs.portfolio

  codeBuildConsole:
    Description: "CodeBuild Project Console URL"
    Value: !Sub "https://console.aws.amazon.com/codesuite/codebuild/projects?region=${AWS::Region}"

  bucketHail:
    Description: "Hail S3 bucket"
    Value: !GetAtt core.Outputs.bucketHail

  bucketSageMaker:
    Description: "SageMaker S3 bucket"
    Value: !GetAtt core.Outputs.bucketSageMaker
